name: untitled1
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  bcrypt: 1.1.3
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.1
  uuid: ^3.0.6
  intl: ^0.18.0

  # Firebase Packages
  firebase_core: ^2.32.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.17.5
  firebase_database: ^10.5.7
  firebase_storage: ^11.6.5
  firebase_messaging: ^14.7.10
  cloud_functions: ^4.7.6

  # Autres paquets utiles
  intl_phone_field: ^3.2.0
  font_awesome_flutter: ^10.7.0
  image_picker: ^1.0.7
  path_provider: ^2.0.0
  vibration: ^2.0.0
  rxdart: ^0.27.7
  animated_background: ^2.0.0

  # Pour les animations simples
  simple_animations: 5.1.0

  # Lottie pour les animations sur iOS
  lottie: ^3.3.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/lotties/
    - assets/images/
    - assets/images/sport11.jpg
    - assets/images/sport22.jpg
    - assets/images/sport44.jpg
    - assets/images/terrain.jpg
    - assets/images/jersey.png
